spring.application.name=chartmania
spring.config.import=optional:file:.env[.properties]

spring.thymeleaf.cache=false

logging.level.org.springframework.security=TRACE

chart.upload.directory=${CHART_UPLOAD_DIRECTORY:/Users/alessio/Desktop/Progetti/personali/chartmania/uploads/charts}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/chartmania}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

secure.cookie=${SECURE_COOKIE:false}

jwt.secret=${JWT_SECRET}
jwt.issuer=${JWT_ISSUER:chartmania-api}
jwt.exp-minutes=${JWT_EXP_MINUTES:80}
jwt.refresh.token.exp-minutes=${JWT_REFRESH_TOKEN_EXP_MINUTES:14400}

allowed.origin=${ALLOWED_ORIGIN:http://localhost:5173}
